### ISSUE TITLE
Not able to build ..

### ISSUE THREAD

**Issue by DarpanJain** [zambezi/grid#7]
## Not able to build .Invalid name @zambezi/grid

Please give detailed build steps. 

Also is it possible to use this grid as a react component in reactjs project (being complied using webpack rather than grunt)?

**Comment by FabienDeshayes** [comment]
Hi @DarpanJain ,

We're actually working on a React wrapper for this that should be available to you soon. Hopefully this should help you building it.

We will also provide build steps - the documentation will improve as we add more features and continue working on it.

Thanks!

**Comment by gabrielmontagne** [comment]
Hi @DarpanJain , which version of npm are you using?  We are using [https://docs.npmjs.com/getting-started/scoped-packages](scoped npm packages) on this project, which require npm version 2.7.0 or greater.

To build the package -- and you're totally right, the docs are just stubbed for the time being -- you should be able to just do:

```
npm i
npm run build
```

To use this component in your own project, provided you have an up to date version of npm, you should be able to just add it as a dependency ( `npm i -S @zambezi/grid` ), import it in your code ( `import { createGrid } from '@zambezi/grid` ) and use it ( `var grid = createGrid()` ).  Your packaging solution -- webpack in your case -- should be able to pick that up and bundle the component as well as all that the component itself needs.

**Comment by mstade** [comment]
@gabrielmontagne is that entirely true? I tried to get it running yesterday, but found @zambezi/d3-utils and @zambezi/fun weren't really buildable as such (the grunt build seems wrong) and the deployed versions did not have the files that your example looks for (i.e. the bundles.) I'm looking at fixing that today though, and in the process making them ES2015 modules.

**Comment by gabrielmontagne** [comment]
the grid uses "@next" versions of those two libraries -- not 'master' --
which don't use grunt at all. They build fine, and they install fine as
dependencies when you pull the grid in.  these are much reduced versions of
the libraries, but perhaps we could merge and grow them back little by
little

**Comment by mstade** [comment]
Oh, you mean the [fun@version-2-ground-work](https://github.com/zambezi/fun/tree/version-2-groundwork) and [d3-utils@version-3-ground-work](https://github.com/zambezi/d3-utils/tree/version-3-ground-work) branches? In that case yeah, we defo should merge. Do you want to start the PRs or should I?

**Comment by gabrielmontagne** [comment]
go for it! I'm away and typing from a roaming phone : )

**Comment by mstade** [comment]
Haha excellent, I'll get the PRs sorted.

**Comment by gabrielmontagne** [comment]
Seems to be building fine now.  @DarpanJain , please don't hesitate to bring back if you still have problems.
